/* $TOG: XmStrDefs22.ht /main/2 1997/06/18 17:50:15 samborn $ */
#ifndef _XmStrDefs22_h_
#define _XmStrDefs22_h_

#include <X11/Intrinsic.h>

#ifndef _XmConst
#define _XmConst /**/
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* $TOG: makestrs.c /main/11 1998/02/06 11:24:15 kaleb $ */
/* This file is automatically generated. */
/* Default ABI version -- Do not edit */
/* TOG: xmstring.list /main/5 1997/06/20 08:37:02 samborn */

#ifdef XMSTRINGDEFINES
#define XmCAllowUnusedSpace "AllowUnusedSpace"
#define XmNallowUnusedSpace "allowUnusedSpace"
#define XmNitemFoundCallback "itemFoundCallback"
#define XmNitemNotFoundCallback "itemNotFoundCallback"
#define XmRXmTabSide "XmTabSide"
#define XmRTabSide "TabSide"
#define XmRXmPixmapPlacement "XmPixmapPlacement"
#define XmRXmPixmap "XmPixmap"
#define XmRXmPixel "XmPixel"
#define XmRXmIconPlacement "XmIconPlacement"
#define XmRXmHierarchyNodeState "XmHierarchyNodeState"
#define XmRXmFillOption "XmFillOption"
#define XmRXmConnectStyle "XmConnectStyle"
#define XmRXmColorMode "XmColorMode"
#define XmRXmAlignment "XmAlignment"
#define XmRTabStyle "TabStyle"
#define XmRTabOrientation "TabOrientation"
#define XmRTabMode "TabMode"
#define XmRTabList "TabList"
#define XmRTabEdge "TabEdge"
#define XmRTabArrowPlacement "TabArrowPlacement"
#define XmNxlfdString "xlfdString"
#define XmNverticalNodeSpace "verticalNodeSpace"
#define XmNverticalMargin "verticalMargin"
#define XmNverifyTextFailedCallback "verifyTextFailedCallback"
#define XmNverifyTextCallback "verifyTextCallback"
#define XmNverify "verify"
#define XmNvalues "values"
#define XmNuseTextField "useTextField"
#define XmNuseScaling "useScaling"
#define XmNuseImageCache "useImageCache"
#define XmNupdateTextCallback "updateTextCallback"
#define XmNupdateShellCallback "updateShellCallback"
#define XmNunselectCallback "unselectCallback"
#define XmNuniformTabSize "uniformTabSize"
#define XmNtraversalIndex "traversalIndex"
#define XmNtitleString "titleString"
#define XmNtextString "textString"
#define XmNtextRows "textRows"
#define XmNtearOffLabelString "tearOffLabelString"
#define XmNtabTearOffEnabled "tabTearOffEnabled"
#define XmNtabStyle "tabStyle"
#define XmNtabStringDirection "tabStringDirection"
#define XmNtabSide "tabSide"
#define XmNtabSelectedCallback "tabSelectedCallback"
#define XmNtabSelectPixmap "tabSelectPixmap"
#define XmNtabSelectColor "tabSelectColor"
#define XmNtabPixmapPlacement "tabPixmapPlacement"
#define XmNtabOrientation "tabOrientation"
#define XmNtabOffset "tabOffset"
#define XmNtabMode "tabMode"
#define XmNtabMarginWidth "tabMarginWidth"
#define XmNtabMarginHeight "tabMarginHeight"
#define XmNtabList "tabList"
#define XmNtabLabelString "tabLabelString"
#define XmNtabLabelSpacing "tabLabelSpacing"
#define XmNtabLabelPixmap "tabLabelPixmap"
#define XmNtabForeground "tabForeground"
#define XmNtabEdge "tabEdge"
#define XmNtabCornerPercent "tabCornerPercent"
#define XmNtabBoxWidget "tabBoxWidget"
#define XmNtabBackgroundPixmap "tabBackgroundPixmap"
#define XmNtabBackground "tabBackground"
#define XmNtabAutoSelect "tabAutoSelect"
#define XmNtabArrowPlacement "tabArrowPlacement"
#define XmNtabAlignment "tabAlignment"
#define XmNstackedEffect "stackedEffect"
#define XmNsortFunctions "sortFunctions"
#define XmNsliderTogLabel "sliderTogLabel"
#define XmNsizeString "sizeString"
#define XmNshowValue "showValue"
#define XmNshowSash "showSash"
#define XmNshowNameString "showNameString"
#define XmNshowLabel "showLabel"
#define XmNshowFontName "showFontName"
#define XmNshowFind "showFind"
#define XmNselectedIndex "selectedIndex"
#define XmNselectedColumn "selectedColumn"
#define XmNselectCallback "selectCallback"
#define XmNscalingString "scalingString"
#define XmNsashTranslations "sashTranslations"
#define XmNsampleText "sampleText"
#define XmNrgbFile "rgbFile"
#define XmNresizeToPreferred "resizeToPreferred"
#define XmNresizeCallback "resizeCallback"
#define XmNredSliderLabel "redSliderLabel"
#define XmNpropSpaceString "propSpaceString"
#define XmNpreferredPaneSize "preferredPaneSize"
#define XmNposition "position"
#define XmNpopupShellWidget "popupShellWidget"
#define XmNpopupOffset "popupOffset"
#define XmNpopupCursor "popupCursor"
#define XmNpixmapWidth "pixmapWidth"
#define XmNpixmapHeight "pixmapHeight"
#define XmNparentNode "parentNode"
#define XmNotherString "otherString"
#define XmNoptionString "optionString"
#define XmNopenFolderPixmap "openFolderPixmap"
#define XmNopenClosePadding "openClosePadding"
#define XmNnumValues "numValues"
#define XmNnumStacks "numStacks"
#define XmNnumRows "numRows"
#define XmNnodeStateChangedCallback "nodeStateChangedCallback"
#define XmNnodeStateCallback "nodeStateCallback"
#define XmNnodeStateBegEndCallback "nodeStateBegEndCallback"
#define XmNnodeState "nodeState"
#define XmNnoCellError "noCellError"
#define XmNmonoSpaceString "monoSpaceString"
#define XmNminimumVerticalCells "minimumVerticalCells"
#define XmNminimumHorizontalCells "minimumHorizontalCells"
#define XmNminimumCellWidth "minimumCellWidth"
#define XmNminimumCellHeight "minimumCellHeight"
#define XmNmargin "margin"
#define XmNlist "list"
#define XmNlineWidth "lineWidth"
#define XmNlineColor "lineColor"
#define XmNlabel "label"
#define XmNitalicString "italicString"
#define XmNinsertBefore "insertBefore"
#define XmNindentSpace "indentSpace"
#define XmNiconTextPadding "iconTextPadding"
#define XmNiconPlacement "iconPlacement"
#define XmNhorizontalNodeSpace "horizontalNodeSpace"
#define XmNhorizontalMargin "horizontalMargin"
#define XmNgreenSliderLabel "greenSliderLabel"
#define XmNfreeTabPixmap "freeTabPixmap"
#define XmNfirstRow "firstRow"
#define XmNfirstColumnPixmaps "firstColumnPixmaps"
#define XmNfirstColumn "firstColumn"
#define XmNfindLabel "findLabel"
#define XmNfillOption "fillOption"
#define XmNfileReadError "fileReadError"
#define XmNfamilyString "familyString"
#define XmNequalSize "equalSize"
#define XmNentryLabelString "entryLabelString"
#define XmNentryData "entryData"
#define XmNencodingString "encodingString"
#define XmNencodingList "encodingList"
#define XmNdoubleClickCallback "doubleClickCallback"
#define XmNdefaultEncodingString "defaultEncodingString"
#define XmNdFieldPrefWidth "dFieldPrefWidth"
#define XmNdFieldPrefHeight "dFieldPrefHeight"
#define XmNdFieldMinWidth "dFieldMinWidth"
#define XmNdFieldMinHeight "dFieldMinHeight"
#define XmNdFieldMaxWidth "dFieldMaxWidth"
#define XmNdFieldMaxHeight "dFieldMaxHeight"
#define XmNcustomizedCombinationBox "customizedCombinationBox"
#define XmNcursor "cursor"
#define XmNcurrentFont "currentFont"
#define XmNconnectStyle "connectStyle"
#define XmNcomboTranslations "comboTranslations"
#define XmNcolumnTitles "columnTitles"
#define XmNcolorName "colorName"
#define XmNcolorMode "colorMode"
#define XmNcolorListTogLabel "colorListTogLabel"
#define XmNcellY "cellY"
#define XmNcellX "cellX"
#define XmNbothString "bothString"
#define XmNboldString "boldString"
#define XmNblueSliderLabel "blueSliderLabel"
#define XmCDistribution "Distribution"
#define XmCFillStyle "FillStyle"
#define XmCItemSpacing "ItemSpacing"
#define XmCLabelSpacing "LabelSpacing"
#define XmCShowLabel "ShowLabel"
#define XmCStretchable "Stretchable"
#define XmNdefaultEntryLabelAlignment "defaultEntryLabelAlignment"
#define XmNdefaultEntryLabelFontList "defaultEntryLabelFontList"
#define XmNdefaultFillStyle "defaultFillStyle"
#define XmNdistribution "distribution"
#define XmNentryLabelAlignment "entryLabelAlignment"
#define XmNentryLabelFontList "entryLabelFontList"
#define XmNentryLabelPixmap "entryLabelPixmap"
#define XmNentryLabelType "entryLabelType"
#define XmNfillStyle "fillStyle"
#define XmNitemSpacing "itemSpacing"
#define XmNlabelSpacing "labelSpacing"
#define XmNshowEntryLabel "showEntryLabel"
#define XmNstretchable "stretchable"
#define XmRDistribution "Distribution"
#define XmRFillStyle "FillStyle"
#define XmCEqualSize "EqualSize"
#define XmCFillOption "FillOption"
#define XmCColorMode "ColorMode"
#define XmCFileReadError "FileReadError"
#define XmCNoCellError "NoCellError"
#define XmCSliderLabel "SliderLabel"
#define XmCTogLabel "TogLabel"
#define XmCAutoFill "AutoFill"
#define XmCPicture "Picture"
#define XmNautoFill "autoFill"
#define XmNpicture "picture"
#define XmNpictureErrorCallback "pictureErrorCallback"
#define XmNvalidateCallback "validateCallback"
#define XmCFindLabel "FindLabel"
#define XmCShowFind "ShowFind"
#define XmNentryBackground "entryBackground"
#define XmCColumnTitles "ColumnTitles"
#define XmCEntryData "EntryData"
#define XmCFirstColumnPixmaps "FirstColumnPixmaps"
#define XmCFirstLocation "FirstLocation"
#define XmCNewVisualStyle "NewVisualStyle"
#define XmCNumRows "NumRows"
#define XmCScrollBar "ScrollBar"
#define XmCSelectedColumn "SelectedColumn"
#define XmNnewVisualStyle "newVisualStyle"
#define XmCPreferredPaneSize "PreferredPaneSize"
#define XmCShowSash "ShowSash"
#define XmC100DPIString "100DPIString"
#define XmC75DPIString "75DPIString"
#define XmCAnyLowerString "AnyLowerString"
#define XmCAnyString "AnyString"
#define XmCBoldString "BoldString"
#define XmCBothString "BothString"
#define XmCDefaultEncodingString "DefaultEncodingString"
#define XmCEncodingList "EncodingList"
#define XmCEncodingString "EncodingString"
#define XmCFamilyString "FamilyString"
#define XmCItalicString "ItalicString"
#define XmCMonoSpaceString "MonoSpaceString"
#define XmCOptionString "OptionString"
#define XmCOtherString "OtherString"
#define XmCPropSpaceString "PropSpaceString"
#define XmCSampleText "SampleText"
#define XmCScalingString "ScalingString"
#define XmCShowNameString "ShowNameString"
#define XmCSizeString "SizeString"
#define XmCTextRows "TextRows"
#define XmCXlfdSpaceString "XlfdSpaceString"
#define XmN100DPIstring "100DPIstring"
#define XmN75DPIstring "75DPIstring"
#define XmNanyLowerString "anyLowerString"
#define XmNanyString "anyString"
#define XmCCellX "CellX"
#define XmCCellY "CellY"
#define XmCDefaultCells "DefaultCells"
#define XmCMinimumCellSize "MinimumCellSize"
#define XmCIconPlacement "IconPlacement"
#define XmNpixmapDepth "pixmapDepth"
#define XmCAutoClose "AutoClose"
#define XmCInsertBefore "InsertBefore"
#define XmCNodeState "NodeState"
#define XmCNodeStateCallback "NodeStateCallback"
#define XmCNodeStateChangedCallback "NodeStateChangedCallback"
#define XmCParentNode "ParentNode"
#define XmNautoClose "autoClose"
#define XmNcloseFolderPixmap "closeFolderPixmap"
#define XmNnodeCloseFolderPixmap "nodeCloseFolderPixmap"
#define XmNnodeOpenFolderPixmap "nodeOpenFolderPixmap"
#define XmNnodeStateBeginEndCallback "nodeStateBeginEndCallback"
#define XmCConstrainWidth "ConstrainWidth"
#define XmCIndentSpace "IndentSpace"
#define XmNconnectNodes "connectNodes"
#define XmNconstrainWidth "constrainWidth"
#define XmCNumStacks "NumStacks"
#define XmCSelectedIndex "SelectedIndex"
#define XmCStackedEffect "StackedEffect"
#define XmCTabAutoSelect "TabAutoSelect"
#define XmCTabCornerPercent "TabCornerPercent"
#define XmCTabEdge "TabEdge"
#define XmCTabLabelSpacing "TabLabelSpacing"
#define XmCTabMode "TabMode"
#define XmCTabOffset "TabOffset"
#define XmCTabOrientation "TabOrientation"
#define XmCTabSelectColor "TabSelectColor"
#define XmCTabSelectPixmap "TabSelectPixmap"
#define XmCTabStyle "TabStyle"
#define XmCTraversalIndex "TraversalIndex"
#define XmCUniformTabSize "UniformTabSize"
#define XmCUseImageCache "UseImageCache"
#define XmCFreeTabPixmap "FreeTabPixmap"
#define XmCICSEnhancementPakResourceError "ICSEnhancementPakResourceError"
#define XmCTabLabelPixmap "TabLabelPixmap"
#define XmCTabLabelString "TabLabelString"
#define XmCTabPixmapPlacement "TabPixmapPlacement"
#define XmCTabSide "TabSide"
#define XmNillegalResourceValue "illegalResourceValue"
#define XmCCompressStyle "CompressStyle"
#define XmCConnectStyle "ConnectStyle"
#define XmCHorizontalDelta "HorizontalDelta"
#define XmCLineWidth "LineWidth"
#define XmCOpenClosePadding "OpenClosePadding"
#define XmCVerticalDelta "VerticalDelta"
#define XmNcompressStyle "compressStyle"
#define XmNhorizontalDelta "horizontalDelta"
#define XmNlineBackgroundColor "lineBackgroundColor"
#define XmNlineStyle "lineStyle"
#define XmNverticalDelta "verticalDelta"
#define XmRXmCompressStyle "XmCompressStyle"
#define XmRXmLineStyle "XmLineStyle"
#define XmCPopupOffset "PopupOffset"
#define XmCUseTextField "UseTextField"
#define XmCVerify "Verify"
#else
externalref _XmConst char _XmStrings22[];
#ifndef XmCAllowUnusedSpace
#define XmCAllowUnusedSpace ((char*)&_XmStrings22[0])
#endif
#ifndef XmNallowUnusedSpace
#define XmNallowUnusedSpace ((char*)&_XmStrings22[17])
#endif
#ifndef XmNitemFoundCallback
#define XmNitemFoundCallback ((char*)&_XmStrings22[34])
#endif
#ifndef XmNitemNotFoundCallback
#define XmNitemNotFoundCallback ((char*)&_XmStrings22[52])
#endif
#ifndef XmRXmTabSide
#define XmRXmTabSide ((char*)&_XmStrings22[73])
#endif
#ifndef XmRTabSide
#define XmRTabSide ((char*)&_XmStrings22[83])
#endif
#ifndef XmRXmPixmapPlacement
#define XmRXmPixmapPlacement ((char*)&_XmStrings22[91])
#endif
#ifndef XmRXmPixmap
#define XmRXmPixmap ((char*)&_XmStrings22[109])
#endif
#ifndef XmRXmPixel
#define XmRXmPixel ((char*)&_XmStrings22[118])
#endif
#ifndef XmRXmIconPlacement
#define XmRXmIconPlacement ((char*)&_XmStrings22[126])
#endif
#ifndef XmRXmHierarchyNodeState
#define XmRXmHierarchyNodeState ((char*)&_XmStrings22[142])
#endif
#ifndef XmRXmFillOption
#define XmRXmFillOption ((char*)&_XmStrings22[163])
#endif
#ifndef XmRXmConnectStyle
#define XmRXmConnectStyle ((char*)&_XmStrings22[176])
#endif
#ifndef XmRXmColorMode
#define XmRXmColorMode ((char*)&_XmStrings22[191])
#endif
#ifndef XmRXmAlignment
#define XmRXmAlignment ((char*)&_XmStrings22[203])
#endif
#ifndef XmRTabStyle
#define XmRTabStyle ((char*)&_XmStrings22[215])
#endif
#ifndef XmRTabOrientation
#define XmRTabOrientation ((char*)&_XmStrings22[224])
#endif
#ifndef XmRTabMode
#define XmRTabMode ((char*)&_XmStrings22[239])
#endif
#ifndef XmRTabList
#define XmRTabList ((char*)&_XmStrings22[247])
#endif
#ifndef XmRTabEdge
#define XmRTabEdge ((char*)&_XmStrings22[255])
#endif
#ifndef XmRTabArrowPlacement
#define XmRTabArrowPlacement ((char*)&_XmStrings22[263])
#endif
#ifndef XmNxlfdString
#define XmNxlfdString ((char*)&_XmStrings22[281])
#endif
#ifndef XmNverticalNodeSpace
#define XmNverticalNodeSpace ((char*)&_XmStrings22[292])
#endif
#ifndef XmNverticalMargin
#define XmNverticalMargin ((char*)&_XmStrings22[310])
#endif
#ifndef XmNverifyTextFailedCallback
#define XmNverifyTextFailedCallback ((char*)&_XmStrings22[325])
#endif
#ifndef XmNverifyTextCallback
#define XmNverifyTextCallback ((char*)&_XmStrings22[350])
#endif
#ifndef XmNverify
#define XmNverify ((char*)&_XmStrings22[369])
#endif
#ifndef XmNvalues
#define XmNvalues ((char*)&_XmStrings22[376])
#endif
#ifndef XmNuseTextField
#define XmNuseTextField ((char*)&_XmStrings22[383])
#endif
#ifndef XmNuseScaling
#define XmNuseScaling ((char*)&_XmStrings22[396])
#endif
#ifndef XmNuseImageCache
#define XmNuseImageCache ((char*)&_XmStrings22[407])
#endif
#ifndef XmNupdateTextCallback
#define XmNupdateTextCallback ((char*)&_XmStrings22[421])
#endif
#ifndef XmNupdateShellCallback
#define XmNupdateShellCallback ((char*)&_XmStrings22[440])
#endif
#ifndef XmNunselectCallback
#define XmNunselectCallback ((char*)&_XmStrings22[460])
#endif
#ifndef XmNuniformTabSize
#define XmNuniformTabSize ((char*)&_XmStrings22[477])
#endif
#ifndef XmNtraversalIndex
#define XmNtraversalIndex ((char*)&_XmStrings22[492])
#endif
#ifndef XmNtitleString
#define XmNtitleString ((char*)&_XmStrings22[507])
#endif
#ifndef XmNtextString
#define XmNtextString ((char*)&_XmStrings22[519])
#endif
#ifndef XmNtextRows
#define XmNtextRows ((char*)&_XmStrings22[530])
#endif
#ifndef XmNtearOffLabelString
#define XmNtearOffLabelString ((char*)&_XmStrings22[539])
#endif
#ifndef XmNtabTearOffEnabled
#define XmNtabTearOffEnabled ((char*)&_XmStrings22[558])
#endif
#ifndef XmNtabStyle
#define XmNtabStyle ((char*)&_XmStrings22[576])
#endif
#ifndef XmNtabStringDirection
#define XmNtabStringDirection ((char*)&_XmStrings22[585])
#endif
#ifndef XmNtabSide
#define XmNtabSide ((char*)&_XmStrings22[604])
#endif
#ifndef XmNtabSelectedCallback
#define XmNtabSelectedCallback ((char*)&_XmStrings22[612])
#endif
#ifndef XmNtabSelectPixmap
#define XmNtabSelectPixmap ((char*)&_XmStrings22[632])
#endif
#ifndef XmNtabSelectColor
#define XmNtabSelectColor ((char*)&_XmStrings22[648])
#endif
#ifndef XmNtabPixmapPlacement
#define XmNtabPixmapPlacement ((char*)&_XmStrings22[663])
#endif
#ifndef XmNtabOrientation
#define XmNtabOrientation ((char*)&_XmStrings22[682])
#endif
#ifndef XmNtabOffset
#define XmNtabOffset ((char*)&_XmStrings22[697])
#endif
#ifndef XmNtabMode
#define XmNtabMode ((char*)&_XmStrings22[707])
#endif
#ifndef XmNtabMarginWidth
#define XmNtabMarginWidth ((char*)&_XmStrings22[715])
#endif
#ifndef XmNtabMarginHeight
#define XmNtabMarginHeight ((char*)&_XmStrings22[730])
#endif
#ifndef XmNtabList
#define XmNtabList ((char*)&_XmStrings22[746])
#endif
#ifndef XmNtabLabelString
#define XmNtabLabelString ((char*)&_XmStrings22[754])
#endif
#ifndef XmNtabLabelSpacing
#define XmNtabLabelSpacing ((char*)&_XmStrings22[769])
#endif
#ifndef XmNtabLabelPixmap
#define XmNtabLabelPixmap ((char*)&_XmStrings22[785])
#endif
#ifndef XmNtabForeground
#define XmNtabForeground ((char*)&_XmStrings22[800])
#endif
#ifndef XmNtabEdge
#define XmNtabEdge ((char*)&_XmStrings22[814])
#endif
#ifndef XmNtabCornerPercent
#define XmNtabCornerPercent ((char*)&_XmStrings22[822])
#endif
#ifndef XmNtabBoxWidget
#define XmNtabBoxWidget ((char*)&_XmStrings22[839])
#endif
#ifndef XmNtabBackgroundPixmap
#define XmNtabBackgroundPixmap ((char*)&_XmStrings22[852])
#endif
#ifndef XmNtabBackground
#define XmNtabBackground ((char*)&_XmStrings22[872])
#endif
#ifndef XmNtabAutoSelect
#define XmNtabAutoSelect ((char*)&_XmStrings22[886])
#endif
#ifndef XmNtabArrowPlacement
#define XmNtabArrowPlacement ((char*)&_XmStrings22[900])
#endif
#ifndef XmNtabAlignment
#define XmNtabAlignment ((char*)&_XmStrings22[918])
#endif
#ifndef XmNstackedEffect
#define XmNstackedEffect ((char*)&_XmStrings22[931])
#endif
#ifndef XmNsortFunctions
#define XmNsortFunctions ((char*)&_XmStrings22[945])
#endif
#ifndef XmNsliderTogLabel
#define XmNsliderTogLabel ((char*)&_XmStrings22[959])
#endif
#ifndef XmNsizeString
#define XmNsizeString ((char*)&_XmStrings22[974])
#endif
#ifndef XmNshowValue
#define XmNshowValue ((char*)&_XmStrings22[985])
#endif
#ifndef XmNshowSash
#define XmNshowSash ((char*)&_XmStrings22[995])
#endif
#ifndef XmNshowNameString
#define XmNshowNameString ((char*)&_XmStrings22[1004])
#endif
#ifndef XmNshowLabel
#define XmNshowLabel ((char*)&_XmStrings22[1019])
#endif
#ifndef XmNshowFontName
#define XmNshowFontName ((char*)&_XmStrings22[1029])
#endif
#ifndef XmNshowFind
#define XmNshowFind ((char*)&_XmStrings22[1042])
#endif
#ifndef XmNselectedIndex
#define XmNselectedIndex ((char*)&_XmStrings22[1051])
#endif
#ifndef XmNselectedColumn
#define XmNselectedColumn ((char*)&_XmStrings22[1065])
#endif
#ifndef XmNselectCallback
#define XmNselectCallback ((char*)&_XmStrings22[1080])
#endif
#ifndef XmNscalingString
#define XmNscalingString ((char*)&_XmStrings22[1095])
#endif
#ifndef XmNsashTranslations
#define XmNsashTranslations ((char*)&_XmStrings22[1109])
#endif
#ifndef XmNsampleText
#define XmNsampleText ((char*)&_XmStrings22[1126])
#endif
#ifndef XmNrgbFile
#define XmNrgbFile ((char*)&_XmStrings22[1137])
#endif
#ifndef XmNresizeToPreferred
#define XmNresizeToPreferred ((char*)&_XmStrings22[1145])
#endif
#ifndef XmNresizeCallback
#define XmNresizeCallback ((char*)&_XmStrings22[1163])
#endif
#ifndef XmNredSliderLabel
#define XmNredSliderLabel ((char*)&_XmStrings22[1178])
#endif
#ifndef XmNpropSpaceString
#define XmNpropSpaceString ((char*)&_XmStrings22[1193])
#endif
#ifndef XmNpreferredPaneSize
#define XmNpreferredPaneSize ((char*)&_XmStrings22[1209])
#endif
#ifndef XmNposition
#define XmNposition ((char*)&_XmStrings22[1227])
#endif
#ifndef XmNpopupShellWidget
#define XmNpopupShellWidget ((char*)&_XmStrings22[1236])
#endif
#ifndef XmNpopupOffset
#define XmNpopupOffset ((char*)&_XmStrings22[1253])
#endif
#ifndef XmNpopupCursor
#define XmNpopupCursor ((char*)&_XmStrings22[1265])
#endif
#ifndef XmNpixmapWidth
#define XmNpixmapWidth ((char*)&_XmStrings22[1277])
#endif
#ifndef XmNpixmapHeight
#define XmNpixmapHeight ((char*)&_XmStrings22[1289])
#endif
#ifndef XmNparentNode
#define XmNparentNode ((char*)&_XmStrings22[1302])
#endif
#ifndef XmNotherString
#define XmNotherString ((char*)&_XmStrings22[1313])
#endif
#ifndef XmNoptionString
#define XmNoptionString ((char*)&_XmStrings22[1325])
#endif
#ifndef XmNopenFolderPixmap
#define XmNopenFolderPixmap ((char*)&_XmStrings22[1338])
#endif
#ifndef XmNopenClosePadding
#define XmNopenClosePadding ((char*)&_XmStrings22[1355])
#endif
#ifndef XmNnumValues
#define XmNnumValues ((char*)&_XmStrings22[1372])
#endif
#ifndef XmNnumStacks
#define XmNnumStacks ((char*)&_XmStrings22[1382])
#endif
#ifndef XmNnumRows
#define XmNnumRows ((char*)&_XmStrings22[1392])
#endif
#ifndef XmNnodeStateChangedCallback
#define XmNnodeStateChangedCallback ((char*)&_XmStrings22[1400])
#endif
#ifndef XmNnodeStateCallback
#define XmNnodeStateCallback ((char*)&_XmStrings22[1425])
#endif
#ifndef XmNnodeStateBegEndCallback
#define XmNnodeStateBegEndCallback ((char*)&_XmStrings22[1443])
#endif
#ifndef XmNnodeState
#define XmNnodeState ((char*)&_XmStrings22[1467])
#endif
#ifndef XmNnoCellError
#define XmNnoCellError ((char*)&_XmStrings22[1477])
#endif
#ifndef XmNmonoSpaceString
#define XmNmonoSpaceString ((char*)&_XmStrings22[1489])
#endif
#ifndef XmNminimumVerticalCells
#define XmNminimumVerticalCells ((char*)&_XmStrings22[1505])
#endif
#ifndef XmNminimumHorizontalCells
#define XmNminimumHorizontalCells ((char*)&_XmStrings22[1526])
#endif
#ifndef XmNminimumCellWidth
#define XmNminimumCellWidth ((char*)&_XmStrings22[1549])
#endif
#ifndef XmNminimumCellHeight
#define XmNminimumCellHeight ((char*)&_XmStrings22[1566])
#endif
#ifndef XmNmargin
#define XmNmargin ((char*)&_XmStrings22[1584])
#endif
#ifndef XmNlist
#define XmNlist ((char*)&_XmStrings22[1591])
#endif
#ifndef XmNlineWidth
#define XmNlineWidth ((char*)&_XmStrings22[1596])
#endif
#ifndef XmNlineColor
#define XmNlineColor ((char*)&_XmStrings22[1606])
#endif
#ifndef XmNlabel
#define XmNlabel ((char*)&_XmStrings22[1616])
#endif
#ifndef XmNitalicString
#define XmNitalicString ((char*)&_XmStrings22[1622])
#endif
#ifndef XmNinsertBefore
#define XmNinsertBefore ((char*)&_XmStrings22[1635])
#endif
#ifndef XmNindentSpace
#define XmNindentSpace ((char*)&_XmStrings22[1648])
#endif
#ifndef XmNiconTextPadding
#define XmNiconTextPadding ((char*)&_XmStrings22[1660])
#endif
#ifndef XmNiconPlacement
#define XmNiconPlacement ((char*)&_XmStrings22[1676])
#endif
#ifndef XmNhorizontalNodeSpace
#define XmNhorizontalNodeSpace ((char*)&_XmStrings22[1690])
#endif
#ifndef XmNhorizontalMargin
#define XmNhorizontalMargin ((char*)&_XmStrings22[1710])
#endif
#ifndef XmNgreenSliderLabel
#define XmNgreenSliderLabel ((char*)&_XmStrings22[1727])
#endif
#ifndef XmNfreeTabPixmap
#define XmNfreeTabPixmap ((char*)&_XmStrings22[1744])
#endif
#ifndef XmNfirstRow
#define XmNfirstRow ((char*)&_XmStrings22[1758])
#endif
#ifndef XmNfirstColumnPixmaps
#define XmNfirstColumnPixmaps ((char*)&_XmStrings22[1767])
#endif
#ifndef XmNfirstColumn
#define XmNfirstColumn ((char*)&_XmStrings22[1786])
#endif
#ifndef XmNfindLabel
#define XmNfindLabel ((char*)&_XmStrings22[1798])
#endif
#ifndef XmNfillOption
#define XmNfillOption ((char*)&_XmStrings22[1808])
#endif
#ifndef XmNfileReadError
#define XmNfileReadError ((char*)&_XmStrings22[1819])
#endif
#ifndef XmNfamilyString
#define XmNfamilyString ((char*)&_XmStrings22[1833])
#endif
#ifndef XmNequalSize
#define XmNequalSize ((char*)&_XmStrings22[1846])
#endif
#ifndef XmNentryLabelString
#define XmNentryLabelString ((char*)&_XmStrings22[1856])
#endif
#ifndef XmNentryData
#define XmNentryData ((char*)&_XmStrings22[1873])
#endif
#ifndef XmNencodingString
#define XmNencodingString ((char*)&_XmStrings22[1883])
#endif
#ifndef XmNencodingList
#define XmNencodingList ((char*)&_XmStrings22[1898])
#endif
#ifndef XmNdoubleClickCallback
#define XmNdoubleClickCallback ((char*)&_XmStrings22[1911])
#endif
#ifndef XmNdefaultEncodingString
#define XmNdefaultEncodingString ((char*)&_XmStrings22[1931])
#endif
#ifndef XmNdFieldPrefWidth
#define XmNdFieldPrefWidth ((char*)&_XmStrings22[1953])
#endif
#ifndef XmNdFieldPrefHeight
#define XmNdFieldPrefHeight ((char*)&_XmStrings22[1969])
#endif
#ifndef XmNdFieldMinWidth
#define XmNdFieldMinWidth ((char*)&_XmStrings22[1986])
#endif
#ifndef XmNdFieldMinHeight
#define XmNdFieldMinHeight ((char*)&_XmStrings22[2001])
#endif
#ifndef XmNdFieldMaxWidth
#define XmNdFieldMaxWidth ((char*)&_XmStrings22[2017])
#endif
#ifndef XmNdFieldMaxHeight
#define XmNdFieldMaxHeight ((char*)&_XmStrings22[2032])
#endif
#ifndef XmNcustomizedCombinationBox
#define XmNcustomizedCombinationBox ((char*)&_XmStrings22[2048])
#endif
#ifndef XmNcursor
#define XmNcursor ((char*)&_XmStrings22[2073])
#endif
#ifndef XmNcurrentFont
#define XmNcurrentFont ((char*)&_XmStrings22[2080])
#endif
#ifndef XmNconnectStyle
#define XmNconnectStyle ((char*)&_XmStrings22[2092])
#endif
#ifndef XmNcomboTranslations
#define XmNcomboTranslations ((char*)&_XmStrings22[2105])
#endif
#ifndef XmNcolumnTitles
#define XmNcolumnTitles ((char*)&_XmStrings22[2123])
#endif
#ifndef XmNcolorName
#define XmNcolorName ((char*)&_XmStrings22[2136])
#endif
#ifndef XmNcolorMode
#define XmNcolorMode ((char*)&_XmStrings22[2146])
#endif
#ifndef XmNcolorListTogLabel
#define XmNcolorListTogLabel ((char*)&_XmStrings22[2156])
#endif
#ifndef XmNcellY
#define XmNcellY ((char*)&_XmStrings22[2174])
#endif
#ifndef XmNcellX
#define XmNcellX ((char*)&_XmStrings22[2180])
#endif
#ifndef XmNbothString
#define XmNbothString ((char*)&_XmStrings22[2186])
#endif
#ifndef XmNboldString
#define XmNboldString ((char*)&_XmStrings22[2197])
#endif
#ifndef XmNblueSliderLabel
#define XmNblueSliderLabel ((char*)&_XmStrings22[2208])
#endif
#ifndef XmCDistribution
#define XmCDistribution ((char*)&_XmStrings22[2224])
#endif
#ifndef XmCFillStyle
#define XmCFillStyle ((char*)&_XmStrings22[2237])
#endif
#ifndef XmCItemSpacing
#define XmCItemSpacing ((char*)&_XmStrings22[2247])
#endif
#ifndef XmCLabelSpacing
#define XmCLabelSpacing ((char*)&_XmStrings22[2259])
#endif
#ifndef XmCShowLabel
#define XmCShowLabel ((char*)&_XmStrings22[2272])
#endif
#ifndef XmCStretchable
#define XmCStretchable ((char*)&_XmStrings22[2282])
#endif
#ifndef XmNdefaultEntryLabelAlignment
#define XmNdefaultEntryLabelAlignment ((char*)&_XmStrings22[2294])
#endif
#ifndef XmNdefaultEntryLabelFontList
#define XmNdefaultEntryLabelFontList ((char*)&_XmStrings22[2321])
#endif
#ifndef XmNdefaultFillStyle
#define XmNdefaultFillStyle ((char*)&_XmStrings22[2347])
#endif
#ifndef XmNdistribution
#define XmNdistribution ((char*)&_XmStrings22[2364])
#endif
#ifndef XmNentryLabelAlignment
#define XmNentryLabelAlignment ((char*)&_XmStrings22[2377])
#endif
#ifndef XmNentryLabelFontList
#define XmNentryLabelFontList ((char*)&_XmStrings22[2397])
#endif
#ifndef XmNentryLabelPixmap
#define XmNentryLabelPixmap ((char*)&_XmStrings22[2416])
#endif
#ifndef XmNentryLabelType
#define XmNentryLabelType ((char*)&_XmStrings22[2433])
#endif
#ifndef XmNfillStyle
#define XmNfillStyle ((char*)&_XmStrings22[2448])
#endif
#ifndef XmNitemSpacing
#define XmNitemSpacing ((char*)&_XmStrings22[2458])
#endif
#ifndef XmNlabelSpacing
#define XmNlabelSpacing ((char*)&_XmStrings22[2470])
#endif
#ifndef XmNshowEntryLabel
#define XmNshowEntryLabel ((char*)&_XmStrings22[2483])
#endif
#ifndef XmNstretchable
#define XmNstretchable ((char*)&_XmStrings22[2498])
#endif
#ifndef XmRDistribution
#define XmRDistribution ((char*)&_XmStrings22[2510])
#endif
#ifndef XmRFillStyle
#define XmRFillStyle ((char*)&_XmStrings22[2523])
#endif
#ifndef XmCEqualSize
#define XmCEqualSize ((char*)&_XmStrings22[2533])
#endif
#ifndef XmCFillOption
#define XmCFillOption ((char*)&_XmStrings22[2543])
#endif
#ifndef XmCColorMode
#define XmCColorMode ((char*)&_XmStrings22[2554])
#endif
#ifndef XmCFileReadError
#define XmCFileReadError ((char*)&_XmStrings22[2564])
#endif
#ifndef XmCNoCellError
#define XmCNoCellError ((char*)&_XmStrings22[2578])
#endif
#ifndef XmCSliderLabel
#define XmCSliderLabel ((char*)&_XmStrings22[2590])
#endif
#ifndef XmCTogLabel
#define XmCTogLabel ((char*)&_XmStrings22[2602])
#endif
#ifndef XmCAutoFill
#define XmCAutoFill ((char*)&_XmStrings22[2611])
#endif
#ifndef XmCPicture
#define XmCPicture ((char*)&_XmStrings22[2620])
#endif
#ifndef XmNautoFill
#define XmNautoFill ((char*)&_XmStrings22[2628])
#endif
#ifndef XmNpicture
#define XmNpicture ((char*)&_XmStrings22[2637])
#endif
#ifndef XmNpictureErrorCallback
#define XmNpictureErrorCallback ((char*)&_XmStrings22[2645])
#endif
#ifndef XmNvalidateCallback
#define XmNvalidateCallback ((char*)&_XmStrings22[2666])
#endif
#ifndef XmCFindLabel
#define XmCFindLabel ((char*)&_XmStrings22[2683])
#endif
#ifndef XmCShowFind
#define XmCShowFind ((char*)&_XmStrings22[2693])
#endif
#ifndef XmNentryBackground
#define XmNentryBackground ((char*)&_XmStrings22[2702])
#endif
#ifndef XmCColumnTitles
#define XmCColumnTitles ((char*)&_XmStrings22[2718])
#endif
#ifndef XmCEntryData
#define XmCEntryData ((char*)&_XmStrings22[2731])
#endif
#ifndef XmCFirstColumnPixmaps
#define XmCFirstColumnPixmaps ((char*)&_XmStrings22[2741])
#endif
#ifndef XmCFirstLocation
#define XmCFirstLocation ((char*)&_XmStrings22[2760])
#endif
#ifndef XmCNewVisualStyle
#define XmCNewVisualStyle ((char*)&_XmStrings22[2774])
#endif
#ifndef XmCNumRows
#define XmCNumRows ((char*)&_XmStrings22[2789])
#endif
#ifndef XmCScrollBar
#define XmCScrollBar ((char*)&_XmStrings22[2797])
#endif
#ifndef XmCSelectedColumn
#define XmCSelectedColumn ((char*)&_XmStrings22[2807])
#endif
#ifndef XmNnewVisualStyle
#define XmNnewVisualStyle ((char*)&_XmStrings22[2822])
#endif
#ifndef XmCPreferredPaneSize
#define XmCPreferredPaneSize ((char*)&_XmStrings22[2837])
#endif
#ifndef XmCShowSash
#define XmCShowSash ((char*)&_XmStrings22[2855])
#endif
#ifndef XmC100DPIString
#define XmC100DPIString ((char*)&_XmStrings22[2864])
#endif
#ifndef XmC75DPIString
#define XmC75DPIString ((char*)&_XmStrings22[2877])
#endif
#ifndef XmCAnyLowerString
#define XmCAnyLowerString ((char*)&_XmStrings22[2889])
#endif
#ifndef XmCAnyString
#define XmCAnyString ((char*)&_XmStrings22[2904])
#endif
#ifndef XmCBoldString
#define XmCBoldString ((char*)&_XmStrings22[2914])
#endif
#ifndef XmCBothString
#define XmCBothString ((char*)&_XmStrings22[2925])
#endif
#ifndef XmCDefaultEncodingString
#define XmCDefaultEncodingString ((char*)&_XmStrings22[2936])
#endif
#ifndef XmCEncodingList
#define XmCEncodingList ((char*)&_XmStrings22[2958])
#endif
#ifndef XmCEncodingString
#define XmCEncodingString ((char*)&_XmStrings22[2971])
#endif
#ifndef XmCFamilyString
#define XmCFamilyString ((char*)&_XmStrings22[2986])
#endif
#ifndef XmCItalicString
#define XmCItalicString ((char*)&_XmStrings22[2999])
#endif
#ifndef XmCMonoSpaceString
#define XmCMonoSpaceString ((char*)&_XmStrings22[3012])
#endif
#ifndef XmCOptionString
#define XmCOptionString ((char*)&_XmStrings22[3028])
#endif
#ifndef XmCOtherString
#define XmCOtherString ((char*)&_XmStrings22[3041])
#endif
#ifndef XmCPropSpaceString
#define XmCPropSpaceString ((char*)&_XmStrings22[3053])
#endif
#ifndef XmCSampleText
#define XmCSampleText ((char*)&_XmStrings22[3069])
#endif
#ifndef XmCScalingString
#define XmCScalingString ((char*)&_XmStrings22[3080])
#endif
#ifndef XmCShowNameString
#define XmCShowNameString ((char*)&_XmStrings22[3094])
#endif
#ifndef XmCSizeString
#define XmCSizeString ((char*)&_XmStrings22[3109])
#endif
#ifndef XmCTextRows
#define XmCTextRows ((char*)&_XmStrings22[3120])
#endif
#ifndef XmCXlfdSpaceString
#define XmCXlfdSpaceString ((char*)&_XmStrings22[3129])
#endif
#ifndef XmN100DPIstring
#define XmN100DPIstring ((char*)&_XmStrings22[3145])
#endif
#ifndef XmN75DPIstring
#define XmN75DPIstring ((char*)&_XmStrings22[3158])
#endif
#ifndef XmNanyLowerString
#define XmNanyLowerString ((char*)&_XmStrings22[3170])
#endif
#ifndef XmNanyString
#define XmNanyString ((char*)&_XmStrings22[3185])
#endif
#ifndef XmCCellX
#define XmCCellX ((char*)&_XmStrings22[3195])
#endif
#ifndef XmCCellY
#define XmCCellY ((char*)&_XmStrings22[3201])
#endif
#ifndef XmCDefaultCells
#define XmCDefaultCells ((char*)&_XmStrings22[3207])
#endif
#ifndef XmCMinimumCellSize
#define XmCMinimumCellSize ((char*)&_XmStrings22[3220])
#endif
#ifndef XmCIconPlacement
#define XmCIconPlacement ((char*)&_XmStrings22[3236])
#endif
#ifndef XmNpixmapDepth
#define XmNpixmapDepth ((char*)&_XmStrings22[3250])
#endif
#ifndef XmCAutoClose
#define XmCAutoClose ((char*)&_XmStrings22[3262])
#endif
#ifndef XmCInsertBefore
#define XmCInsertBefore ((char*)&_XmStrings22[3272])
#endif
#ifndef XmCNodeState
#define XmCNodeState ((char*)&_XmStrings22[3285])
#endif
#ifndef XmCNodeStateCallback
#define XmCNodeStateCallback ((char*)&_XmStrings22[3295])
#endif
#ifndef XmCNodeStateChangedCallback
#define XmCNodeStateChangedCallback ((char*)&_XmStrings22[3313])
#endif
#ifndef XmCParentNode
#define XmCParentNode ((char*)&_XmStrings22[3338])
#endif
#ifndef XmNautoClose
#define XmNautoClose ((char*)&_XmStrings22[3349])
#endif
#ifndef XmNcloseFolderPixmap
#define XmNcloseFolderPixmap ((char*)&_XmStrings22[3359])
#endif
#ifndef XmNnodeCloseFolderPixmap
#define XmNnodeCloseFolderPixmap ((char*)&_XmStrings22[3377])
#endif
#ifndef XmNnodeOpenFolderPixmap
#define XmNnodeOpenFolderPixmap ((char*)&_XmStrings22[3399])
#endif
#ifndef XmNnodeStateBeginEndCallback
#define XmNnodeStateBeginEndCallback ((char*)&_XmStrings22[3420])
#endif
#ifndef XmCConstrainWidth
#define XmCConstrainWidth ((char*)&_XmStrings22[3446])
#endif
#ifndef XmCIndentSpace
#define XmCIndentSpace ((char*)&_XmStrings22[3461])
#endif
#ifndef XmNconnectNodes
#define XmNconnectNodes ((char*)&_XmStrings22[3473])
#endif
#ifndef XmNconstrainWidth
#define XmNconstrainWidth ((char*)&_XmStrings22[3486])
#endif
#ifndef XmCNumStacks
#define XmCNumStacks ((char*)&_XmStrings22[3501])
#endif
#ifndef XmCSelectedIndex
#define XmCSelectedIndex ((char*)&_XmStrings22[3511])
#endif
#ifndef XmCStackedEffect
#define XmCStackedEffect ((char*)&_XmStrings22[3525])
#endif
#ifndef XmCTabAutoSelect
#define XmCTabAutoSelect ((char*)&_XmStrings22[3539])
#endif
#ifndef XmCTabCornerPercent
#define XmCTabCornerPercent ((char*)&_XmStrings22[3553])
#endif
#ifndef XmCTabEdge
#define XmCTabEdge ((char*)&_XmStrings22[3570])
#endif
#ifndef XmCTabLabelSpacing
#define XmCTabLabelSpacing ((char*)&_XmStrings22[3578])
#endif
#ifndef XmCTabMode
#define XmCTabMode ((char*)&_XmStrings22[3594])
#endif
#ifndef XmCTabOffset
#define XmCTabOffset ((char*)&_XmStrings22[3602])
#endif
#ifndef XmCTabOrientation
#define XmCTabOrientation ((char*)&_XmStrings22[3612])
#endif
#ifndef XmCTabSelectColor
#define XmCTabSelectColor ((char*)&_XmStrings22[3627])
#endif
#ifndef XmCTabSelectPixmap
#define XmCTabSelectPixmap ((char*)&_XmStrings22[3642])
#endif
#ifndef XmCTabStyle
#define XmCTabStyle ((char*)&_XmStrings22[3658])
#endif
#ifndef XmCTraversalIndex
#define XmCTraversalIndex ((char*)&_XmStrings22[3667])
#endif
#ifndef XmCUniformTabSize
#define XmCUniformTabSize ((char*)&_XmStrings22[3682])
#endif
#ifndef XmCUseImageCache
#define XmCUseImageCache ((char*)&_XmStrings22[3697])
#endif
#ifndef XmCFreeTabPixmap
#define XmCFreeTabPixmap ((char*)&_XmStrings22[3711])
#endif
#ifndef XmCICSEnhancementPakResourceError
#define XmCICSEnhancementPakResourceError ((char*)&_XmStrings22[3725])
#endif
#ifndef XmCTabLabelPixmap
#define XmCTabLabelPixmap ((char*)&_XmStrings22[3756])
#endif
#ifndef XmCTabLabelString
#define XmCTabLabelString ((char*)&_XmStrings22[3771])
#endif
#ifndef XmCTabPixmapPlacement
#define XmCTabPixmapPlacement ((char*)&_XmStrings22[3786])
#endif
#ifndef XmCTabSide
#define XmCTabSide ((char*)&_XmStrings22[3805])
#endif
#ifndef XmNillegalResourceValue
#define XmNillegalResourceValue ((char*)&_XmStrings22[3813])
#endif
#ifndef XmCCompressStyle
#define XmCCompressStyle ((char*)&_XmStrings22[3834])
#endif
#ifndef XmCConnectStyle
#define XmCConnectStyle ((char*)&_XmStrings22[3848])
#endif
#ifndef XmCHorizontalDelta
#define XmCHorizontalDelta ((char*)&_XmStrings22[3861])
#endif
#ifndef XmCLineWidth
#define XmCLineWidth ((char*)&_XmStrings22[3877])
#endif
#ifndef XmCOpenClosePadding
#define XmCOpenClosePadding ((char*)&_XmStrings22[3887])
#endif
#ifndef XmCVerticalDelta
#define XmCVerticalDelta ((char*)&_XmStrings22[3904])
#endif
#ifndef XmNcompressStyle
#define XmNcompressStyle ((char*)&_XmStrings22[3918])
#endif
#ifndef XmNhorizontalDelta
#define XmNhorizontalDelta ((char*)&_XmStrings22[3932])
#endif
#ifndef XmNlineBackgroundColor
#define XmNlineBackgroundColor ((char*)&_XmStrings22[3948])
#endif
#ifndef XmNlineStyle
#define XmNlineStyle ((char*)&_XmStrings22[3968])
#endif
#ifndef XmNverticalDelta
#define XmNverticalDelta ((char*)&_XmStrings22[3978])
#endif
#ifndef XmRXmCompressStyle
#define XmRXmCompressStyle ((char*)&_XmStrings22[3992])
#endif
#ifndef XmRXmLineStyle
#define XmRXmLineStyle ((char*)&_XmStrings22[4008])
#endif
#ifndef XmCPopupOffset
#define XmCPopupOffset ((char*)&_XmStrings22[4020])
#endif
#ifndef XmCUseTextField
#define XmCUseTextField ((char*)&_XmStrings22[4032])
#endif
#ifndef XmCVerify
#define XmCVerify ((char*)&_XmStrings22[4045])
#endif
#endif /* XMSTRINGDEFINES */

#ifdef __cplusplus
}  /* Close scope of 'extern "C"' declaration */
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}  /* Close scope of 'extern "C"' declaration */
#endif

#endif /* _XmStrDefs22_h_ */
